import { Link } from 'react-router-dom';
import { useAuth } from '../auth/auth';

function Home() {
  const { user } = useAuth();

  return (
    <div className="container mt-5 px-4">
      <div className="jumbotron bg-primary text-white p-5 rounded">
        <h1 className="display-4">Welcome to SecureBank</h1>
        <p className="lead">The most secure banking platform with Voice-Based CAPTCHA technology</p>
        <hr className="my-4" />
        <p>Experience next-generation security with multilingual voice verification for all your transactions.</p>
        {!user ? (
          <div>
            <Link className="btn btn-light btn-lg me-3" to="/signup" role="button">Get Started</Link>
            <Link className="btn btn-outline-light btn-lg" to="/login" role="button">Login</Link>
          </div>
        ) : (
          <Link className="btn btn-light btn-lg" to="/dashboard" role="button">Go to Dashboard</Link>
        )}
      </div>

      <div className="row mt-5">
        <div className="col-md-4">
          <h3>🎤 Voice Security</h3>
          <p>Advanced voice biometric verification ensures only you can access your account.</p>
        </div>
        <div className="col-md-4">
          <h3>🌍 Multilingual</h3>
          <p>Support for multiple languages including English, Hindi, Spanish, and French.</p>
        </div>
        <div className="col-md-4">
          <h3>🔒 AI-Powered</h3>
          <p>Personalized security questions generated by advanced AI technology.</p>
        </div>
      </div>
    </div>
  );
}
export default Home;